#### Model Training

In [36]:
import numpy as np
import pandas as pd
import joblib
import data_ingestion
import pipeline
import train_model
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report

import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Importing

In [37]:
query = """
    SELECT review_text, sentiment_label
    FROM reviews;
"""
conn = data_ingestion.get_connection()

In [38]:
df = pd.read_sql_query(query, conn)
df

                                             review_text sentiment_label
0      Barang sudah diterima dengan cepat dan kualita...        positive
1      alat yg sangat bermanfaat untuk melatih skill ...        positive
2      mantap barang sudah diterima .. sesuai dgn yg ...        positive
3                      Good product good service. Thanks        positive
4      transfer tgl 17 barang nya nyampe bali tgl 18....        positive
...                                                  ...             ...
65538                                            Mantapp        positive
65539  Kualitas produk: Kualitas produknya bagus, bua...        positive
65540  packing rapih. produk aman sampai rumah. berfu...        positive
65541                                              Bagus        positive
65542  Rasa: Awas vision terus meningkat Performa: Ba...        positive

[65543 rows x 2 columns]

Data Cleaning (check train_model for detailed funcs)

In [39]:
train_model.clean_df(df)

Checking for any missing value in columns..
No missing value in column 0
No missing value in column 1
Following columns have missing value present: ['None']
-----------------------
Checking for any duplicate rows..
A total of 7460 duplicate rows have been found in the dataset. Removing them..
0 duplicate rows present in the database.
58083 rows left in the database.
-----------------------

                                             review_text sentiment_label
0      Barang sudah diterima dengan cepat dan kualita...        positive
1      alat yg sangat bermanfaat untuk melatih skill ...        positive
2      mantap barang sudah diterima .. sesuai dgn yg ...        positive
3                      Good product good service. Thanks        positive
4      transfer tgl 17 barang nya nyampe bali tgl 18....        positive
...                                                  ...             ...
65535  packing rapi, respon n proses kirim cpt.. Reco...        positive
65536             kualitas original dan pemakaian nyaman        positive
65539  Kualitas produk: Kualitas produknya bagus, bua...        positive
65540  packing rapih. produk aman sampai rumah. berfu...        positive
65542  Rasa: Awas vision terus meningkat Performa: Ba...        positive

[58083 rows x 2 columns]

In [40]:
slang_dict = pipeline.initialize_dict("colloquial-indonesian-lexicon.csv")
df["review_text"] = df["review_text"].apply(lambda x : pipeline.clean_review_text(text=x, data_dict=slang_dict))
df.head(5)

                                         review_text sentiment_label
0  barang sudah diterima dengan cepat dan kualita...        positive
1  alat yang sangat bermanfaat untuk melatih skil...        positive
2  mantap barang sudah diterima sesuai dengan yan...        positive
3                   good product good service thanks        positive
4  transfer tanggal 17 barang nya sampai bali tan...        positive

In [41]:
df["sentiment_label"] = df["sentiment_label"].map({"negative" : 0, "neutral" : 1, "positive" : 2})

In [42]:
df[["sentiment_label"]].value_counts()

sentiment_label
2                  56506
0                    790
1                    787
Name: count, dtype: int64

Train-Test split

In [43]:
X = df["review_text"]
y = df["sentiment_label"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True, stratify=y)

Text Vectorizing

In [44]:
indo_stopwords = stopwords.words("indonesian")

In [45]:
vectorizer = TfidfVectorizer(stop_words=indo_stopwords, ngram_range=(1, 2), min_df=3, max_features=15000) # indonesian stop words, unigram and bigram range, minimum document frequency = 3 to ignore one time typo usually, only take into account the top 15000 most impactful words basically

In [46]:
X_train_tfidf = vectorizer.fit_transform(X_train)

c:\Users\User\anaconda3\envs\ecom_nlp_env\Lib\site-packages\sklearn\feature_extraction\text.py:411: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['baiknya', 'berkali', 'kali', 'kurangnya', 'mata', 'olah', 'sekurang', 'setidak', 'tama', 'tidaknya'] not in stop_words.
  warnings.warn(

In [47]:
X_test_tfidf = vectorizer.transform(X_test)

Training

In [48]:
lr_model = LogisticRegression(penalty="l2", class_weight="balanced", C=1.0, max_iter=1000, random_state=42) # l2 (ridge regularization) is the default, class weight balanced is needed since our dependent variable is very unbalanced, regularization strength to 1 since our dataset is very sparse (15000 features is a lot) so C ensures that the model dont overfit (also higher C score reduces the strength), max iter lower than 1000 gives ConvergenceWarning because not enough training iteration for the model to reach optimal convergence when tested
linearsvc_model = LinearSVC(penalty="l2", class_weight="balanced", C=1.0, dual=False, multi_class="ovr", random_state=42) # penalty and class weight follows our LR model. Select the algorithm to either solve the dual or primal optimization problem. Prefer dual=False when n_samples > n_features (from sklearn documentation). our n_samples is around 58k while our n_features is exactly 15k, so dual will be False. ovr is the standard, its also better for text based prediction
# random state for defensive programming practice (reproducibility)

In [49]:
lr_model.fit(X_train_tfidf, y_train)

c:\Users\User\anaconda3\envs\ecom_nlp_env\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

LogisticRegression(class_weight='balanced', max_iter=1000, penalty='l2',
                   random_state=42)

In [50]:
linearsvc_model.fit(X_train_tfidf, y_train)

LinearSVC(class_weight='balanced', dual=False, random_state=42)

Predictions

In [51]:
lr_preds = lr_model.predict(X_test_tfidf)
linearsvc_preds = linearsvc_model.predict(X_test_tfidf)

Evaluation

In [52]:
print("---Logistic Regression---")
print(classification_report(y_test, lr_preds))
print("---Linear SVC---")
print(classification_report(y_test, linearsvc_preds))

---Logistic Regression---
              precision    recall  f1-score   support

           0       0.16      0.43      0.24       158
           1       0.09      0.31      0.14       157
           2       0.99      0.93      0.96     11302

    accuracy                           0.92     11617
   macro avg       0.41      0.56      0.44     11617
weighted avg       0.97      0.92      0.94     11617

---Linear SVC---
              precision    recall  f1-score   support

           0       0.33      0.32      0.32       158
           1       0.16      0.15      0.16       157
           2       0.98      0.98      0.98     11302

    accuracy                           0.96     11617
   macro avg       0.49      0.48      0.49     11617
weighted avg       0.96      0.96      0.96     11617

Precision: Out of all the instances model predicted positive, how many are correct?
Recall (Sensitivity): Out of all actual positives, how many did the model find?
F1-Score is the harmonic mean score of the two.

Precision focuses more on minimizing False Positives.
Recall focuses more on minimizing False Negatives.

Since both precision and recall are equally important here, we can look at our F1-Score. We know our dataset is heavily imbalanced, so judging through our macro avg score, we know that LinearSVC performed better here.

In [55]:
joblib.dump(lr_model, "models/sentiment_lr_model.pkl")
joblib.dump(linearsvc_model, "models/sentiment_linearsvc_model.pkl")
joblib.dump(vectorizer, "models/sentiment_vectorizer.pkl")

['models/sentiment_vectorizer.pkl']